<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="41901" started-at="2017-12-22T01:37:17Z" finished-at="2017-12-22T01:37:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="41901" started-at="2017-12-22T01:37:17Z" finished-at="2017-12-22T01:37:59Z">
      <class name="com.proton.email.bot.core.tests.ProtonTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="setUp" is-config="true" duration-ms="6446" started-at="2017-12-22T03:37:17Z" finished-at="2017-12-22T03:37:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Click_on_Create_Account_TEST()[pri:1, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Click_on_Create_Account_TEST" duration-ms="2679" started-at="2017-12-22T03:37:24Z" finished-at="2017-12-22T03:37:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Click_on_Create_Account_TEST -->
        <test-method status="PASS" signature="Select_free_plan_TEST()[pri:2, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Select_free_plan_TEST" duration-ms="7260" started-at="2017-12-22T03:37:26Z" finished-at="2017-12-22T03:37:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Select_free_plan_TEST -->
        <test-method status="PASS" signature="Fill_form_details_and_create_dotCom_account_TEST()[pri:3, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Fill_form_details_and_create_dotCom_account_TEST" duration-ms="6983" started-at="2017-12-22T03:37:34Z" finished-at="2017-12-22T03:37:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Fill_form_details_and_create_dotCom_account_TEST -->
        <test-method status="FAIL" signature="Confirm_Human_and_Verify_Email()[pri:4, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Confirm_Human_and_Verify_Email" duration-ms="18506" started-at="2017-12-22T03:37:41Z" finished-at="2017-12-22T03:37:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.proton.email.bot.core.tests.ProtonTests.Confirm_Human_and_Verify_Email(ProtonTests.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Confirm_Human_and_Verify_Email -->
        <test-method status="PASS" signature="Verified_Auto_ProtonEmail_Sent()[pri:5, instance:com.proton.email.bot.core.tests.ProtonTests@646d64ab]" name="Verified_Auto_ProtonEmail_Sent" duration-ms="1" started-at="2017-12-22T03:37:59Z" finished-at="2017-12-22T03:37:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verified_Auto_ProtonEmail_Sent -->
      </class> <!-- com.proton.email.bot.core.tests.ProtonTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
